spring:
  datasource:
      url: jdbc:mysql://localhost:3306/tc?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: tc
      password: tc
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
   port: 8080
